// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgVDTtRGLX1ViHN3sY-IKZK0Cm06qvOgw',
    appId: '1:270946605394:android:9f456ae8ef3da3aa61828b',
    messagingSenderId: '270946605394',
    projectId: 'safebox-257ee',
    storageBucket: 'safebox-257ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx0NmjyBAStAnzxIZTeNlpbtssNX0Mz04',
    appId: '1:270946605394:ios:14755dee6db78e7761828b',
    messagingSenderId: '270946605394',
    projectId: 'safebox-257ee',
    storageBucket: 'safebox-257ee.firebasestorage.app',
    androidClientId: '270946605394-kjgn16a5d8hud17nrb961gtojq91fp3b.apps.googleusercontent.com',
    iosClientId: '270946605394-6idoqgfnip0bojj9r6k388k08p7fs2vg.apps.googleusercontent.com',
    iosBundleId: 'com.example.madsSafebox',
  );
}
